export default defineEventHandler(async (event) => {
  const query = getQuery(event)
  const perPage = parseInt((query.perPage as string) || '5', 10)
  const page = parseInt((query.page as string) || '1', 10)
  const filter = (query.filter as string) || ''
  const slug = (query.slug as string) || ''

  if (perPage >= 150) {
    // Create an artificial delay
    await new Promise(resolve => setTimeout(resolve, 1000))
  }

  const data = await getDemoData()
  const recipient = data.find(item => item.slug === slug)

  return {
    total: data.length,
    data: filterDemoData(data, filter, page, perPage),
    recipient,
  }
})

function filterDemoData(
  data: any[],
  filter: string,
  page: number,
  perPage: number,
) {
  const offset = (page - 1) * perPage
  if (!filter) {
    return data.slice(offset, offset + perPage)
  }
  const filterRe = new RegExp(filter, 'i')
  return data
    .filter((item) => {
      return [item.name, item.category].some(item => item.match(filterRe))
    })
    .slice(offset, offset + perPage)
}

async function getDemoData() {
  return Promise.resolve([
    {
      id: 1,
      type: 'company',
      name: 'Airbnb',
      slug: 'airbnb',
      category: 'Housing company',
      picture: '/img/logos/companies/airbnb.svg',
      email: 'hello@airbnb.com',
      status: 'active',
      taxId: 'TX-23413',
      phoneNumber: '+1 202-423-4313',
      language: 'english',
      country: 'United States',
      address: [
        '12, San Stefano Street, Suite 43, 1st floor',
        'Los Angeles, CA 91234',
      ],
      paymentMethod: {
        name: 'stripe',
      },
      transactions: [
        {
          id: 1,
          date: 'May 26, 2023',
          type: 'out',
          amount: 275.31,
          account: '**** 7623',
          status: 'processing',
          method: 'transfer',
        },
        {
          id: 2,
          date: 'Apr 25, 2023',
          type: 'out',
          amount: 112.28,
          account: '**** 7623',
          status: 'complete',
          method: 'transfer',
        },
        {
          id: 3,
          date: 'Mar 23, 2023',
          type: 'out',
          amount: 387.14,
          account: '**** 7623',
          status: 'complete',
          method: 'cheque',
        },
        {
          id: 4,
          date: 'Feb 21, 2023',
          type: 'out',
          amount: 628.12,
          account: '**** 7623',
          status: 'complete',
          method: 'transfer',
        },
        {
          id: 5,
          date: 'Jan 29, 2023',
          type: 'out',
          amount: 153.47,
          account: '**** 7623',
          status: 'complete',
          method: 'transfer',
        },
        {
          id: 6,
          date: 'Nov 15, 2022',
          type: 'out',
          amount: 311.13,
          account: '**** 7623',
          status: 'complete',
          method: 'transfer',
        },
        {
          id: 7,
          date: 'Oct 17, 2022',
          type: 'out',
          amount: 251.39,
          account: '**** 7623',
          status: 'complete',
          method: 'transfer',
        },
        {
          id: 8,
          date: 'Sep 11, 2022',
          type: 'out',
          amount: 742.99,
          account: '**** 7623',
          status: 'complete',
          method: 'transfer',
        },
      ],
    },
    {
      id: 2,
      type: 'person',
      name: 'Jackie Strauss',
      slug: 'jackie-strauss',
      category: 'Freelance worker',
      picture: '/img/avatars/9.svg',
      email: 'jackiestrauss@gmail.com',
      status: 'active',
      taxId: 'TX-392323',
      phoneNumber: '+1 202-555-0176',
      language: 'english',
      country: 'United States',
      address: [
        '148, Victoria Street, Suite D23, 3rd floor',
        'New York, NY 10001',
      ],
      paymentMethod: {
        name: 'paypal',
      },
      transactions: [
        {
          id: 1,
          date: 'May 26, 2023',
          type: 'out',
          amount: 52.14,
          account: '**** 7623',
          status: 'processing',
          method: 'transfer',
        },
        {
          id: 2,
          date: 'Apr 25, 2023',
          type: 'out',
          amount: 428.47,
          account: '**** 7623',
          status: 'complete',
          method: 'transfer',
        },
        {
          id: 3,
          date: 'Mar 23, 2023',
          type: 'out',
          amount: 112.23,
          account: '**** 7623',
          status: 'complete',
          method: 'cheque',
        },
        {
          id: 4,
          date: 'Feb 21, 2023',
          type: 'out',
          amount: 950,
          account: '**** 7623',
          status: 'complete',
          method: 'transfer',
        },
        {
          id: 5,
          date: 'Jan 29, 2023',
          type: 'out',
          amount: 1500,
          account: '**** 7623',
          status: 'complete',
          method: 'transfer',
        },
        {
          id: 6,
          date: 'Nov 15, 2022',
          type: 'out',
          amount: 550,
          account: '**** 7623',
          status: 'complete',
          method: 'transfer',
        },
        {
          id: 7,
          date: 'Oct 17, 2022',
          type: 'out',
          amount: 380,
          account: '**** 7623',
          status: 'complete',
          method: 'transfer',
        },
        {
          id: 8,
          date: 'Sep 11, 2022',
          type: 'out',
          amount: 449.99,
          account: '**** 7623',
          status: 'complete',
          method: 'transfer',
        },
      ],
    },
    {
      id: 3,
      type: 'company',
      name: 'AT&T',
      slug: 'att',
      category: 'Phone company',
      picture: '/img/logos/companies/att.svg',
      email: 'hello@att.com',
      status: 'active',
      taxId: 'TX-231331',
      phoneNumber: '+1 131-424-4828',
      language: 'english',
      country: 'United States',
      address: [
        '42, Brentmann Avenue, Suite 124, 27th floor',
        'Las Vegas, NV 92347',
      ],
      paymentMethod: {
        name: 'stripe',
      },
      transactions: [
        {
          id: 1,
          date: 'May 26, 2023',
          type: 'out',
          amount: 65.99,
          account: '**** 7623',
          status: 'processing',
          method: 'transfer',
        },
        {
          id: 2,
          date: 'Apr 25, 2023',
          type: 'in',
          amount: 59.13,
          account: '**** 7623',
          status: 'complete',
          method: 'transfer',
        },
        {
          id: 3,
          date: 'Apr 24, 2023',
          type: 'out',
          amount: 65.99,
          account: '**** 7623',
          status: 'complete',
          method: 'transfer',
        },
        {
          id: 4,
          date: 'Mar 23, 2023',
          type: 'out',
          amount: 65.99,
          account: '**** 7623',
          status: 'complete',
          method: 'transfer',
        },
        {
          id: 5,
          date: 'Feb 21, 2023',
          type: 'out',
          amount: 65.99,
          account: '**** 7623',
          status: 'complete',
          method: 'transfer',
        },
        {
          id: 6,
          date: 'Jan 29, 2023',
          type: 'out',
          amount: 65.99,
          account: '**** 7623',
          status: 'complete',
          method: 'transfer',
        },
        {
          id: 7,
          date: 'Nov 15, 2022',
          type: 'out',
          amount: 65.99,
          account: '**** 7623',
          status: 'complete',
          method: 'transfer',
        },
        {
          id: 8,
          date: 'Oct 17, 2022',
          type: 'out',
          amount: 65.99,
          account: '**** 7623',
          status: 'complete',
          method: 'transfer',
        },
        {
          id: 9,
          date: 'Sep 11, 2022',
          type: 'out',
          amount: 65.99,
          account: '**** 7623',
          status: 'complete',
          method: 'transfer',
        },
      ],
    },
    {
      id: 4,
      type: 'company',
      name: 'Gitlab',
      slug: 'gitlab',
      category: 'Software company',
      picture: '/img/logos/companies/gitlab.svg',
      email: 'contact@gitlab.com',
      status: 'inactive',
      taxId: 'TX-429932',
      phoneNumber: '+1 131-424-4828',
      language: 'english',
      country: 'United States',
      address: [
        '12, San Marina Highway, Suite U12, 5th floor',
        'Los Angeles, CA 91482',
      ],
      paymentMethod: {
        name: 'stripe',
      },
      transactions: [],
    },
    {
      id: 5,
      type: 'company',
      name: 'Amazon',
      slug: 'amazon',
      category: 'Commerce company',
      picture: '/img/logos/companies/amazon.svg',
      email: 'contact@amazon.com',
      status: 'active',
      taxId: 'TX-849283',
      phoneNumber: '+1 311-423-5231',
      language: 'english',
      country: 'United States',
      address: [
        '14, Manhattan Avenue, Suite 231, 45th floor',
        'New York, NY 84299',
      ],
      paymentMethod: {
        name: 'paypal',
      },
      transactions: [
        {
          id: 1,
          date: 'May 26, 2023',
          type: 'out',
          amount: 382.38,
          account: '**** 7623',
          status: 'complete',
          method: 'transfer',
        },
        {
          id: 2,
          date: 'Apr 25, 2023',
          type: 'in',
          amount: 16.31,
          account: '**** 7623',
          status: 'complete',
          method: 'transfer',
        },
        {
          id: 3,
          date: 'Apr 24, 2023',
          type: 'out',
          amount: 128.28,
          account: '**** 7623',
          status: 'complete',
          method: 'transfer',
        },
        {
          id: 4,
          date: 'Mar 23, 2023',
          type: 'out',
          amount: 31.17,
          account: '**** 7623',
          status: 'complete',
          method: 'transfer',
        },
        {
          id: 5,
          date: 'Feb 21, 2023',
          type: 'out',
          amount: 483.19,
          account: '**** 7623',
          status: 'complete',
          method: 'transfer',
        },
        {
          id: 6,
          date: 'Jan 29, 2023',
          type: 'out',
          amount: 76.87,
          account: '**** 7623',
          status: 'complete',
          method: 'transfer',
        },
        {
          id: 7,
          date: 'Nov 15, 2022',
          type: 'out',
          amount: 12.47,
          account: '**** 7623',
          status: 'complete',
          method: 'transfer',
        },
        {
          id: 8,
          date: 'Oct 17, 2022',
          type: 'out',
          amount: 59.99,
          account: '**** 7623',
          status: 'complete',
          method: 'transfer',
        },
        {
          id: 9,
          date: 'Sep 11, 2022',
          type: 'out',
          amount: 131.48,
          account: '**** 7623',
          status: 'complete',
          method: 'transfer',
        },
      ],
    },
    {
      id: 6,
      type: 'person',
      name: 'Hermann Mayer',
      slug: 'hermann-mayer',
      category: 'Freelance worker',
      picture: '/img/avatars/16.svg',
      email: 'hermannm@gmail.com',
      status: 'active',
      taxId: 'TX-24231',
      phoneNumber: '+1 231-555-2431',
      language: 'english',
      country: 'UK',
      address: ['34, Lord Irons Street, App 44, 3rd floor', 'London, UK 31311'],
      paymentMethod: {
        name: 'paypal',
      },
      transactions: [
        {
          id: 1,
          date: 'May 26, 2023',
          type: 'out',
          amount: 52.14,
          account: '**** 7623',
          status: 'processing',
          method: 'transfer',
        },
        {
          id: 2,
          date: 'Apr 25, 2023',
          type: 'out',
          amount: 428.47,
          account: '**** 7623',
          status: 'complete',
          method: 'transfer',
        },
        {
          id: 3,
          date: 'Mar 23, 2023',
          type: 'out',
          amount: 112.23,
          account: '**** 7623',
          status: 'complete',
          method: 'cheque',
        },
        {
          id: 4,
          date: 'Feb 21, 2023',
          type: 'out',
          amount: 950,
          account: '**** 7623',
          status: 'complete',
          method: 'transfer',
        },
        {
          id: 5,
          date: 'Jan 29, 2023',
          type: 'out',
          amount: 1500,
          account: '**** 7623',
          status: 'complete',
          method: 'transfer',
        },
        {
          id: 6,
          date: 'Nov 15, 2022',
          type: 'out',
          amount: 550,
          account: '**** 7623',
          status: 'complete',
          method: 'transfer',
        },
        {
          id: 7,
          date: 'Oct 17, 2022',
          type: 'out',
          amount: 380,
          account: '**** 7623',
          status: 'complete',
          method: 'transfer',
        },
        {
          id: 8,
          date: 'Sep 11, 2022',
          type: 'out',
          amount: 449.99,
          account: '**** 7623',
          status: 'complete',
          method: 'transfer',
        },
      ],
    },
    {
      id: 7,
      type: 'person',
      name: 'Clark Smith',
      slug: 'clark-smith',
      category: 'Freelance worker',
      picture: '/img/avatars/15.svg',
      email: 'karlsmith@gmail.com',
      status: 'active',
      taxId: 'TX-4231',
      phoneNumber: '+1 231-555-2431',
      language: 'english',
      country: 'Germany',
      address: ['41, Frichenhauer blvd, App 11, 1st floor', 'Berlin, DE 47584'],
      paymentMethod: {
        name: 'stripe',
      },
      transactions: [
        {
          id: 1,
          date: 'May 26, 2023',
          type: 'out',
          amount: 52.14,
          account: '**** 7623',
          status: 'processing',
          method: 'transfer',
        },
        {
          id: 2,
          date: 'Apr 25, 2023',
          type: 'out',
          amount: 428.47,
          account: '**** 7623',
          status: 'complete',
          method: 'transfer',
        },
        {
          id: 3,
          date: 'Mar 23, 2023',
          type: 'out',
          amount: 112.23,
          account: '**** 7623',
          status: 'complete',
          method: 'cheque',
        },
        {
          id: 4,
          date: 'Feb 21, 2023',
          type: 'out',
          amount: 950,
          account: '**** 7623',
          status: 'complete',
          method: 'transfer',
        },
        {
          id: 5,
          date: 'Jan 29, 2023',
          type: 'out',
          amount: 1500,
          account: '**** 7623',
          status: 'complete',
          method: 'transfer',
        },
        {
          id: 6,
          date: 'Nov 15, 2022',
          type: 'out',
          amount: 550,
          account: '**** 7623',
          status: 'complete',
          method: 'transfer',
        },
        {
          id: 7,
          date: 'Oct 17, 2022',
          type: 'out',
          amount: 380,
          account: '**** 7623',
          status: 'complete',
          method: 'transfer',
        },
        {
          id: 8,
          date: 'Sep 11, 2022',
          type: 'out',
          amount: 449.99,
          account: '**** 7623',
          status: 'complete',
          method: 'transfer',
        },
      ],
    },
    {
      id: 8,
      type: 'person',
      name: 'Aaron Patterson',
      slug: 'aaron-patterson',
      category: 'Freelance worker',
      picture: '/img/avatars/14.svg',
      email: 'aaronp@gmail.com',
      status: 'active',
      taxId: 'TX-32332',
      phoneNumber: '+1 231-555-2431',
      language: 'english',
      country: 'United States',
      address: [
        '35, Reinmann Street, Block C4, 2nd floor',
        'San Diego, CA 91342',
      ],
      paymentMethod: {
        name: 'stripe',
      },
      transactions: [
        {
          id: 1,
          date: 'May 26, 2023',
          type: 'out',
          amount: 52.14,
          account: '**** 7623',
          status: 'processing',
          method: 'transfer',
        },
        {
          id: 2,
          date: 'Apr 25, 2023',
          type: 'out',
          amount: 428.47,
          account: '**** 7623',
          status: 'complete',
          method: 'transfer',
        },
        {
          id: 3,
          date: 'Mar 23, 2023',
          type: 'out',
          amount: 112.23,
          account: '**** 7623',
          status: 'complete',
          method: 'cheque',
        },
        {
          id: 4,
          date: 'Feb 21, 2023',
          type: 'out',
          amount: 950,
          account: '**** 7623',
          status: 'complete',
          method: 'transfer',
        },
        {
          id: 5,
          date: 'Jan 29, 2023',
          type: 'out',
          amount: 1500,
          account: '**** 7623',
          status: 'complete',
          method: 'transfer',
        },
        {
          id: 6,
          date: 'Nov 15, 2022',
          type: 'out',
          amount: 550,
          account: '**** 7623',
          status: 'complete',
          method: 'transfer',
        },
        {
          id: 7,
          date: 'Oct 17, 2022',
          type: 'out',
          amount: 380,
          account: '**** 7623',
          status: 'complete',
          method: 'transfer',
        },
        {
          id: 8,
          date: 'Sep 11, 2022',
          type: 'out',
          amount: 449.99,
          account: '**** 7623',
          status: 'complete',
          method: 'transfer',
        },
      ],
    },
    {
      id: 9,
      type: 'person',
      name: 'John Carillo',
      slug: 'john-carillo',
      category: 'Freelance worker',
      picture: '/img/avatars/1.svg',
      email: 'carilloj@gmail.com',
      status: 'active',
      taxId: 'TX-42442',
      phoneNumber: '+1 231-555-2431',
      language: 'english',
      country: 'United States',
      address: [
        '35, Reinmann Street, Suite A2, 1st floor',
        'San Francisco, CA 91342',
      ],
      paymentMethod: {
        name: 'paypal',
      },
      transactions: [
        {
          id: 1,
          date: 'May 26, 2023',
          type: 'out',
          amount: 52.14,
          account: '**** 7623',
          status: 'processing',
          method: 'transfer',
        },
        {
          id: 2,
          date: 'Apr 25, 2023',
          type: 'out',
          amount: 428.47,
          account: '**** 7623',
          status: 'complete',
          method: 'transfer',
        },
        {
          id: 3,
          date: 'Mar 23, 2023',
          type: 'out',
          amount: 112.23,
          account: '**** 7623',
          status: 'complete',
          method: 'cheque',
        },
        {
          id: 4,
          date: 'Feb 21, 2023',
          type: 'out',
          amount: 950,
          account: '**** 7623',
          status: 'complete',
          method: 'transfer',
        },
        {
          id: 5,
          date: 'Jan 29, 2023',
          type: 'out',
          amount: 1500,
          account: '**** 7623',
          status: 'complete',
          method: 'transfer',
        },
        {
          id: 6,
          date: 'Nov 15, 2022',
          type: 'out',
          amount: 550,
          account: '**** 7623',
          status: 'complete',
          method: 'transfer',
        },
        {
          id: 7,
          date: 'Oct 17, 2022',
          type: 'out',
          amount: 380,
          account: '**** 7623',
          status: 'complete',
          method: 'transfer',
        },
        {
          id: 8,
          date: 'Sep 11, 2022',
          type: 'out',
          amount: 449.99,
          account: '**** 7623',
          status: 'complete',
          method: 'transfer',
        },
      ],
    },
    {
      id: 10,
      type: 'person',
      name: 'Kendra Wilson',
      slug: 'kendra-wilson',
      category: 'Freelance worker',
      picture: '/img/avatars/10.svg',
      email: 'kendraw@gmail.com',
      status: 'active',
      taxId: 'TX-54422',
      phoneNumber: '+1 123-424-6244',
      language: 'english',
      country: 'United States',
      address: [
        '2, San Roque Roadway, Block B2, Suite B24',
        'Los Angeles, CA 91342',
      ],
      paymentMethod: {
        name: 'paypal',
      },
      transactions: [
        {
          id: 1,
          date: 'May 26, 2023',
          type: 'out',
          amount: 52.14,
          account: '**** 7623',
          status: 'processing',
          method: 'transfer',
        },
        {
          id: 2,
          date: 'Apr 25, 2023',
          type: 'out',
          amount: 428.47,
          account: '**** 7623',
          status: 'complete',
          method: 'transfer',
        },
        {
          id: 3,
          date: 'Mar 23, 2023',
          type: 'out',
          amount: 112.23,
          account: '**** 7623',
          status: 'complete',
          method: 'cheque',
        },
        {
          id: 4,
          date: 'Feb 21, 2023',
          type: 'out',
          amount: 950,
          account: '**** 7623',
          status: 'complete',
          method: 'transfer',
        },
        {
          id: 5,
          date: 'Jan 29, 2023',
          type: 'out',
          amount: 1500,
          account: '**** 7623',
          status: 'complete',
          method: 'transfer',
        },
        {
          id: 6,
          date: 'Nov 15, 2022',
          type: 'out',
          amount: 550,
          account: '**** 7623',
          status: 'complete',
          method: 'transfer',
        },
        {
          id: 7,
          date: 'Oct 17, 2022',
          type: 'out',
          amount: 380,
          account: '**** 7623',
          status: 'complete',
          method: 'transfer',
        },
        {
          id: 8,
          date: 'Sep 11, 2022',
          type: 'out',
          amount: 449.99,
          account: '**** 7623',
          status: 'complete',
          method: 'transfer',
        },
      ],
    },
    {
      id: 11,
      type: 'person',
      name: 'Howard Streim',
      slug: 'howard-streim',
      category: 'Freelance worker',
      picture: '/img/avatars/20.svg',
      email: 'hstreim@gmail.com',
      status: 'inactive',
      taxId: 'TX-3234',
      phoneNumber: '+1 123-424-6244',
      language: 'english',
      country: 'United States',
      address: [
        '34, San Emiliano Road, Block C3, Suite C56',
        'Los Angeles, CA 91342',
      ],
      paymentMethod: {
        name: 'paypal',
      },
      transactions: [],
    },
    {
      id: 12,
      type: 'person',
      name: 'Anna Lopez',
      slug: 'anna-lopez',
      category: 'Freelance worker',
      picture: '/img/avatars/21.svg',
      email: 'alopez@gmail.com',
      status: 'active',
      taxId: 'TX-428983',
      phoneNumber: '+1 123-424-6244',
      language: 'english',
      country: 'United States',
      address: [
        '76, Reinmann Street, Block D2, 1st floor',
        'San Diego, CA 91342',
      ],
      paymentMethod: {
        name: 'paypal',
      },
      transactions: [
        {
          id: 1,
          date: 'May 26, 2023',
          type: 'out',
          amount: 52.14,
          account: '**** 7623',
          status: 'processing',
          method: 'transfer',
        },
        {
          id: 2,
          date: 'Apr 25, 2023',
          type: 'out',
          amount: 428.47,
          account: '**** 7623',
          status: 'complete',
          method: 'transfer',
        },
        {
          id: 3,
          date: 'Mar 23, 2023',
          type: 'out',
          amount: 112.23,
          account: '**** 7623',
          status: 'complete',
          method: 'cheque',
        },
        {
          id: 4,
          date: 'Feb 21, 2023',
          type: 'out',
          amount: 950,
          account: '**** 7623',
          status: 'complete',
          method: 'transfer',
        },
        {
          id: 5,
          date: 'Jan 29, 2023',
          type: 'out',
          amount: 1500,
          account: '**** 7623',
          status: 'complete',
          method: 'transfer',
        },
        {
          id: 6,
          date: 'Nov 15, 2022',
          type: 'out',
          amount: 550,
          account: '**** 7623',
          status: 'complete',
          method: 'transfer',
        },
        {
          id: 7,
          date: 'Oct 17, 2022',
          type: 'out',
          amount: 380,
          account: '**** 7623',
          status: 'complete',
          method: 'transfer',
        },
        {
          id: 8,
          date: 'Sep 11, 2022',
          type: 'out',
          amount: 449.99,
          account: '**** 7623',
          status: 'complete',
          method: 'transfer',
        },
      ],
    },
    {
      id: 13,
      type: 'company',
      name: 'Atlassian',
      slug: 'atlassian',
      category: 'Software company',
      picture: '/img/logos/companies/atlassian.svg',
      email: 'hello@atlassian.com',
      status: 'active',
      taxId: 'TX-423255',
      phoneNumber: '+1 342-533-6343',
      language: 'english',
      country: 'Australia',
      address: [
        '15, Harrison Avenue, Suite 23, 7th floor',
        'Melbourne, AU 42839',
      ],
      paymentMethod: {
        name: 'stripe',
      },
      transactions: [
        {
          id: 1,
          date: 'May 26, 2023',
          type: 'out',
          amount: 65.99,
          account: '**** 7623',
          status: 'processing',
          method: 'transfer',
        },
        {
          id: 2,
          date: 'Apr 25, 2023',
          type: 'in',
          amount: 59.13,
          account: '**** 7623',
          status: 'complete',
          method: 'transfer',
        },
        {
          id: 3,
          date: 'Apr 24, 2023',
          type: 'out',
          amount: 65.99,
          account: '**** 7623',
          status: 'complete',
          method: 'transfer',
        },
        {
          id: 4,
          date: 'Mar 23, 2023',
          type: 'out',
          amount: 65.99,
          account: '**** 7623',
          status: 'complete',
          method: 'transfer',
        },
        {
          id: 5,
          date: 'Feb 21, 2023',
          type: 'out',
          amount: 65.99,
          account: '**** 7623',
          status: 'complete',
          method: 'transfer',
        },
        {
          id: 6,
          date: 'Jan 29, 2023',
          type: 'out',
          amount: 65.99,
          account: '**** 7623',
          status: 'complete',
          method: 'transfer',
        },
        {
          id: 7,
          date: 'Nov 15, 2022',
          type: 'out',
          amount: 65.99,
          account: '**** 7623',
          status: 'complete',
          method: 'transfer',
        },
        {
          id: 8,
          date: 'Oct 17, 2022',
          type: 'out',
          amount: 65.99,
          account: '**** 7623',
          status: 'complete',
          method: 'transfer',
        },
        {
          id: 9,
          date: 'Sep 11, 2022',
          type: 'out',
          amount: 65.99,
          account: '**** 7623',
          status: 'complete',
          method: 'transfer',
        },
      ],
    },
    {
      id: 14,
      type: 'company',
      name: 'Monday',
      slug: 'monday',
      category: 'Software company',
      picture: '/img/logos/companies/monday.svg',
      email: 'contact@monday.com',
      status: 'active',
      taxId: 'TX-8763',
      phoneNumber: '+1 342-533-6343',
      language: 'english',
      country: 'United States',
      address: [
        '15, Manhattan Avenue, Suite 54, 17th floor',
        'New York, NY 87362',
      ],
      paymentMethod: {
        name: 'stripe',
      },
      transactions: [
        {
          id: 1,
          date: 'May 26, 2023',
          type: 'out',
          amount: 65.99,
          account: '**** 7623',
          status: 'processing',
          method: 'transfer',
        },
        {
          id: 2,
          date: 'Apr 25, 2023',
          type: 'in',
          amount: 59.13,
          account: '**** 7623',
          status: 'complete',
          method: 'transfer',
        },
        {
          id: 3,
          date: 'Apr 24, 2023',
          type: 'out',
          amount: 65.99,
          account: '**** 7623',
          status: 'complete',
          method: 'transfer',
        },
        {
          id: 4,
          date: 'Mar 23, 2023',
          type: 'out',
          amount: 65.99,
          account: '**** 7623',
          status: 'complete',
          method: 'transfer',
        },
        {
          id: 5,
          date: 'Feb 21, 2023',
          type: 'out',
          amount: 65.99,
          account: '**** 7623',
          status: 'complete',
          method: 'transfer',
        },
        {
          id: 6,
          date: 'Jan 29, 2023',
          type: 'out',
          amount: 65.99,
          account: '**** 7623',
          status: 'complete',
          method: 'transfer',
        },
        {
          id: 7,
          date: 'Nov 15, 2022',
          type: 'out',
          amount: 65.99,
          account: '**** 7623',
          status: 'complete',
          method: 'transfer',
        },
        {
          id: 8,
          date: 'Oct 17, 2022',
          type: 'out',
          amount: 65.99,
          account: '**** 7623',
          status: 'complete',
          method: 'transfer',
        },
        {
          id: 9,
          date: 'Sep 11, 2022',
          type: 'out',
          amount: 65.99,
          account: '**** 7623',
          status: 'complete',
          method: 'transfer',
        },
      ],
    },
    {
      id: 15,
      type: 'company',
      name: 'UPS',
      slug: 'ups',
      category: 'Logitics company',
      picture: '/img/logos/companies/ups.svg',
      email: 'contact@ups.com',
      status: 'active',
      taxId: 'TX-762623',
      phoneNumber: '+1 143-546-4212',
      language: 'english',
      country: 'United States',
      address: [
        '14, Church Street, Block D56, 3rd floor',
        'New York, NY 84299',
      ],
      paymentMethod: {
        name: 'paypal',
      },
      transactions: [
        {
          id: 1,
          date: 'May 26, 2023',
          type: 'out',
          amount: 382.38,
          account: '**** 7623',
          status: 'complete',
          method: 'transfer',
        },
        {
          id: 2,
          date: 'Apr 25, 2023',
          type: 'in',
          amount: 16.31,
          account: '**** 7623',
          status: 'complete',
          method: 'transfer',
        },
        {
          id: 3,
          date: 'Apr 24, 2023',
          type: 'out',
          amount: 128.28,
          account: '**** 7623',
          status: 'complete',
          method: 'transfer',
        },
        {
          id: 4,
          date: 'Mar 23, 2023',
          type: 'out',
          amount: 31.17,
          account: '**** 7623',
          status: 'complete',
          method: 'transfer',
        },
        {
          id: 5,
          date: 'Feb 21, 2023',
          type: 'out',
          amount: 483.19,
          account: '**** 7623',
          status: 'complete',
          method: 'transfer',
        },
        {
          id: 6,
          date: 'Jan 29, 2023',
          type: 'out',
          amount: 76.87,
          account: '**** 7623',
          status: 'complete',
          method: 'transfer',
        },
        {
          id: 7,
          date: 'Nov 15, 2022',
          type: 'out',
          amount: 12.47,
          account: '**** 7623',
          status: 'complete',
          method: 'transfer',
        },
        {
          id: 8,
          date: 'Oct 17, 2022',
          type: 'out',
          amount: 59.99,
          account: '**** 7623',
          status: 'complete',
          method: 'transfer',
        },
        {
          id: 9,
          date: 'Sep 11, 2022',
          type: 'out',
          amount: 131.48,
          account: '**** 7623',
          status: 'complete',
          method: 'transfer',
        },
      ],
    },
    {
      id: 16,
      type: 'company',
      name: 'Spotify',
      slug: 'spotify',
      category: 'Software company',
      picture: '/img/logos/companies/spotify.svg',
      email: 'hello@spotify.com',
      status: 'active',
      taxId: 'TX-422413',
      phoneNumber: '+1 276-133-5242',
      language: 'english',
      country: 'United States',
      address: [
        '42, San Sebastian Avenue, Suite 32, 3rd floor',
        'Los Angeles, CA 92746',
      ],
      paymentMethod: {
        name: 'paypal',
      },
      transactions: [
        {
          id: 1,
          date: 'May 26, 2023',
          type: 'out',
          amount: 65.99,
          account: '**** 7623',
          status: 'processing',
          method: 'transfer',
        },
        {
          id: 2,
          date: 'Apr 25, 2023',
          type: 'in',
          amount: 59.13,
          account: '**** 7623',
          status: 'complete',
          method: 'transfer',
        },
        {
          id: 3,
          date: 'Apr 24, 2023',
          type: 'out',
          amount: 65.99,
          account: '**** 7623',
          status: 'complete',
          method: 'transfer',
        },
        {
          id: 4,
          date: 'Mar 23, 2023',
          type: 'out',
          amount: 65.99,
          account: '**** 7623',
          status: 'complete',
          method: 'transfer',
        },
        {
          id: 5,
          date: 'Feb 21, 2023',
          type: 'out',
          amount: 65.99,
          account: '**** 7623',
          status: 'complete',
          method: 'transfer',
        },
        {
          id: 6,
          date: 'Jan 29, 2023',
          type: 'out',
          amount: 65.99,
          account: '**** 7623',
          status: 'complete',
          method: 'transfer',
        },
        {
          id: 7,
          date: 'Nov 15, 2022',
          type: 'out',
          amount: 65.99,
          account: '**** 7623',
          status: 'complete',
          method: 'transfer',
        },
        {
          id: 8,
          date: 'Oct 17, 2022',
          type: 'out',
          amount: 65.99,
          account: '**** 7623',
          status: 'complete',
          method: 'transfer',
        },
        {
          id: 9,
          date: 'Sep 11, 2022',
          type: 'out',
          amount: 65.99,
          account: '**** 7623',
          status: 'complete',
          method: 'transfer',
        },
      ],
    },
  ])
}
